name:                tablebot
version:             0.3.2
github:              "WarwickTabletop/tablebot"
license:             MIT
author:              "Warwick Tabletop"
maintainer:          "tagarople@gmail.com"
copyright:           "2021 Warwick Tabletop"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tagarople/tablebot#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- emoji
- text
- text-icu
- transformers
- load-env
- megaparsec
- persistent
- persistent-sqlite
- persistent-template
- random
- esqueleto
- monad-logger
- time
- aeson
- bytestring
- yaml
- http-conduit
- raw-strings-qq
- template-haskell
- timezone-olson
- duckling
- unordered-containers
- bytestring
- req
- http-client
- data-default
- exception-transformers
- resourcet
- resource-pool
- containers
- th-printf
- mtl
- safe
- edit-distance
- unliftio
- split
- regex-pcre

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost
  - LambdaCase
  - EmptyDataDecls
  - FlexibleContexts
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
  - DerivingStrategies
  - StandaloneDeriving
  - UndecidableInstances
  - DataKinds
  - FlexibleInstances
  - DeriveGeneric
  - TypeApplications
  - MultiWayIf
  - TupleSections
  - ConstraintKinds
  - RecordWildCards
  - ScopedTypeVariables
  - TypeOperators
  - RankNTypes
  ghc-options:
  - -Wall


executables:
  tablebot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tablebot

tests:
  tablebot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tablebot
