name:                tablebot
version:             0.1.0.0
github:              "finnbar/tablebot"
license:             BSD3
author:              "Finnbar Keating"
maintainer:          "finnjkeating@gmail.com"
copyright:           "2021 Finnbar Keating"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/finnbar/tablebot#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- emoji
- text
- transformers
- load-env
- megaparsec
- persistent
- persistent-sqlite
- persistent-template
- esqueleto
- monad-logger
- time

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost
  - LambdaCase
  - EmptyDataDecls
  - FlexibleContexts
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
  - DerivingStrategies
  - StandaloneDeriving
  - UndecidableInstances
  - DataKinds
  - FlexibleInstances


executables:
  tablebot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tablebot

tests:
  tablebot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tablebot
