name: Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v4
